<?php

namespace TrafficCore\Postback;

/**
 * Port of legacy `Component\Postback\Postback`
 * (application/Component/Postback/Postback.php) — extracts/normalizes the
 * conversion fields out of the raw incoming postback request params
 * (query + body, merged the same way `TrafficCore\Pipeline\Signal::
 * fromRequest()` does — GET wins on key collision).
 *
 * Ported field-by-field, using the exact legacy alias lists (copied
 * verbatim from `Postback.php`, not re-derived):
 *  - sub_id aliases: `Component\Conversions\Service\ConversionsService::
 *    getSubIdAliases()` (application/Component/Conversions/Service/
 *    ConversionsService.php) — `trackID, subid, sub_id, subaccount,
 *    aff_sub, clickid, subId, SubID, trackingCodes`.
 *  - tid aliases: `_tidNames` — `tid, transaction_id, txid, trans_id,
 *    receipt`.
 *  - cost aliases: `_costNames` — `cost`.
 *  - revenue/payout aliases: `_payoutNames` — `revenue, profit, payout,
 *    summ_approved, payment, amount, order_sum, order_amount,
 *    affiliateCommission, value`.
 *  - status default variation lists: `_statuses` — sale/rejected/ignore
 *    arrays, each overridable per-request via `sale_status`/`lead_status`/
 *    `rejected_status`/`ignore_status` comma-separated params (ported
 *    exactly, including the "no match found -> stays lead" fallthrough
 *    quirk — see `_findStatus()` below).
 *
 * Explicitly SKIPPED (out of scope per task):
 *  - `_checkMcWap()` / `_checkLimonbucks()` — two specific ad-network
 *    payload-reshaping quirks (application/Component/Postback/Postback.php
 *    `_checkMcWap`/`_checkLimonbucks`). Not called here at all.
 *  - Currency (`_currency` / `getRevenueCalculated()`'s
 *    `CurrencyService::exchange()` branch) — traffic-core has no
 *    currency-conversion infra anywhere (confirmed project-wide). Revenue
 *    and cost are stored exactly as parsed, no conversion.
 *  - `_filterSubId()`'s `:`-delimited multi-subid splitting and the
 *    `NxNx`-prefix `x`->`-` rewrite (legacy quirks for one specific
 *    integration format) — not needed for the sub_id lookup this project
 *    does (`clicks.sub_id` is an opaque random hex token generated by
 *    `BuildRawClickStage`, never `:`-delimited or `NxNx`-prefixed).
 *
 * DEVIATION from legacy `_findRevenue()`/`_findCost()`: legacy casts
 * revenue to `(int) $value` (`$this->_revenue = (int) $value;`), silently
 * truncating any cents. `conversions.revenue` in this project's schema is
 * `decimal(10,4)` — truncating fractional payouts would be a real
 * regression for a real-money feature, not a faithful "port", so this
 * class casts to `float` instead of `int` for both revenue and cost. Cost
 * is left completely uncast in legacy (kept as a string after the
 * comma->dot replace); cast to `float` here for the same reason.
 *
 * DEVIATION from legacy `_findConversionDateTime()`: legacy's loop has a
 * real bug — the "numeric timestamp" branch builds `$customDate` and
 * `return`s without ever assigning it to `$this->_datetime`, and the
 * catch block references `$customDate` from a *previous* loop iteration
 * (undefined on the first). Reproducing that bug faithfully would mean
 * the date-name params never actually take effect, which is clearly not
 * the intent. This port instead: tries each date-name param in order,
 * treats a numeric value as a unix timestamp, otherwise attempts
 * `strtotime()`; accepts the parsed date only if it's within
 * `MAX_YEARS` (2) of "now", else falls back to "now" — same intent as
 * legacy's `MAX_YEARS` guard, without the assignment bug.
 */
class Postback
{
    public const MAX_YEARS = 2;

    private const SUB_ID_ALIASES = [
        'trackID', 'subid', 'sub_id', 'subaccount', 'aff_sub', 'clickid', 'subId', 'SubID', 'trackingCodes',
    ];

    private const TID_NAMES = ['tid', 'transaction_id', 'txid', 'trans_id', 'receipt'];

    private const COST_NAMES = ['cost'];

    private const PAYOUT_NAMES = [
        'revenue', 'profit', 'payout', 'summ_approved', 'payment', 'amount',
        'order_sum', 'order_amount', 'affiliateCommission', 'value',
    ];

    private const DATE_NAMES = ['conversion_time', 'action_time', 'postback_date', 'datetime', 'time'];

    private const STATUS_SALE = 'sale';
    private const STATUS_LEAD = 'lead';
    private const STATUS_REJECTED = 'rejected';
    private const STATUS_IGNORE = 'ignore';

    private const DEFAULT_STATUS_VARIATIONS = [
        self::STATUS_SALE => [
            'approved', '1', 'done', 'confirm', 'confirmed', 'paid', 'rebill', 'sale', 'signup',
            'payed', 'awarded', 'sell', 'sms', 'birj', 'redeem', 'cgbk', 'insf', 'test_sale',
        ],
        self::STATUS_REJECTED => [
            'failure', 'reject', 'cancelled', 'refund', 'cancel', 'decline', 'declined', 'rejected',
            'invalid', 'canceled', 'trash',
        ],
        self::STATUS_IGNORE => [
            'unsubscribe', 'subscribeOff', 'off', 'rfnd', 'cancel-rebill', 'test_rfnd', 'cancel-test-rebill',
        ],
    ];

    /** @var array<string,mixed> */
    private array $params;

    private ?string $subId = null;
    private ?string $tid = null;
    private \DateTimeImmutable $datetime;
    private string $status;
    private ?string $originalStatus = null;
    private float $cost = 0.0;
    private float $revenue = 0.0;

    /** @param array<string,mixed> $params */
    private function __construct(array $params)
    {
        $this->params = $params;
        $this->datetime = new \DateTimeImmutable('now', new \DateTimeZone('UTC'));
        $this->status = self::STATUS_LEAD;
    }

    /** @param array<string,mixed> $params */
    public static function buildFromParams(array $params): self
    {
        $postback = new self($params);
        $postback->subId = $postback->findSubId();
        $postback->datetime = $postback->findConversionDateTime();
        $postback->tid = $postback->findFirstParam(self::TID_NAMES);
        $postback->revenue = $postback->findRevenue();
        $postback->status = $postback->findStatus($postback->originalStatus);
        $postback->cost = $postback->findCost();

        return $postback;
    }

    public function getSubId(): ?string
    {
        return $this->subId;
    }

    public function setSubId(?string $subId): void
    {
        $this->subId = $subId;
    }

    public function getTid(): ?string
    {
        return $this->tid;
    }

    /** @return array<string,mixed> */
    public function getParams(): array
    {
        return $this->params;
    }

    public function getDateTime(): \DateTimeImmutable
    {
        return $this->datetime;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function getOriginalStatus(): ?string
    {
        return $this->originalStatus;
    }

    public function getRevenue(): float
    {
        return $this->revenue;
    }

    public function getCost(): float
    {
        return $this->cost;
    }

    public function hasCost(): bool
    {
        return $this->findFirstParam(self::COST_NAMES) !== null;
    }

    public function isSale(): bool
    {
        return $this->status === self::STATUS_SALE;
    }

    public function isLead(): bool
    {
        return $this->status === self::STATUS_LEAD;
    }

    public function isRejected(): bool
    {
        return $this->status === self::STATUS_REJECTED;
    }

    public function isIgnore(): bool
    {
        return $this->status === self::STATUS_IGNORE;
    }

    private function findFirstParam(array $names): ?string
    {
        foreach ($names as $name) {
            if (isset($this->params[$name]) && $this->params[$name] !== '') {
                return (string) $this->params[$name];
            }
        }

        return null;
    }

    private function findSubId(): ?string
    {
        return $this->findFirstParam(self::SUB_ID_ALIASES);
    }

    private function findRevenue(): float
    {
        $raw = $this->findFirstParam(self::PAYOUT_NAMES);
        if ($raw === null) {
            return 0.0;
        }

        return (float) str_replace(',', '.', $raw);
    }

    private function findCost(): float
    {
        $raw = $this->findFirstParam(self::COST_NAMES);
        if ($raw === null) {
            return 0.0;
        }

        return (float) str_replace(',', '.', $raw);
    }

    /**
     * Ported from `_findStatus()`. Default (no `status` param at all) is
     * `sale`. If a `status` param IS present but matches none of the
     * (possibly request-overridden) variation lists, it falls through to
     * `lead` — that's a literal legacy behavior, not an omission: the
     * initial `$this->_status = LEAD` assignment is never reached by the
     * override loop when nothing matches.
     */
    private function findStatus(?string &$originalStatus): string
    {
        $rawStatus = isset($this->params['status']) && $this->params['status'] !== ''
            ? (string) $this->params['status']
            : null;

        $originalStatus = $rawStatus;

        if ($rawStatus === null) {
            return self::STATUS_SALE;
        }

        $variations = self::DEFAULT_STATUS_VARIATIONS;
        foreach (['sale_status' => self::STATUS_SALE, 'lead_status' => self::STATUS_LEAD, 'ignore_status' => self::STATUS_IGNORE, 'rejected_status' => self::STATUS_REJECTED] as $paramName => $statusKey) {
            if (isset($this->params[$paramName]) && $this->params[$paramName] !== '') {
                $variations[$statusKey] = explode(',', strtolower(urldecode((string) $this->params[$paramName])));
            }
        }

        $matched = self::STATUS_LEAD;
        foreach ($variations as $status => $names) {
            if (in_array(strtolower($rawStatus), $names, true)) {
                $matched = $status;
            }
        }

        return $matched;
    }

    private function findConversionDateTime(): \DateTimeImmutable
    {
        $now = new \DateTimeImmutable('now', new \DateTimeZone('UTC'));

        foreach (self::DATE_NAMES as $name) {
            if (!isset($this->params[$name]) || $this->params[$name] === '') {
                continue;
            }

            $raw = (string) $this->params[$name];
            $candidate = null;

            if (is_numeric($raw)) {
                $candidate = (new \DateTimeImmutable('now', new \DateTimeZone('UTC')))->setTimestamp((int) $raw);
            } else {
                $timestamp = strtotime($raw);
                if ($timestamp !== false) {
                    $candidate = (new \DateTimeImmutable('now', new \DateTimeZone('UTC')))->setTimestamp($timestamp);
                }
            }

            if ($candidate !== null && abs((int) $candidate->format('Y') - (int) $now->format('Y')) <= self::MAX_YEARS) {
                return $candidate;
            }
        }

        return $now;
    }
}
